In [94]:
def TrueRange(high, low, preClose):
    return max([abs(high-low), abs(high-preClose), abs(preClose-low)])

def DX_inc(plusDI, minusDI):
    return 100 * abs(plusDI - minusDI) / (plusDI + minusDI)

def DX(high, low, close, n = 14):
    deltahigh = np.full_like(high, fill_value=np.nan)
    deltalow = np.full_like(high, fill_value=np.nan)
    plusdm = np.full_like(high, fill_value=np.nan)
    minusdm = np.full_like(high, fill_value=np.nan)
    admplus = np.full_like(high, fill_value=np.nan)
    admminus = np.full_like(high, fill_value=np.nan)
    tr = np.full_like(high, fill_value=np.nan)
    atr = np.full_like(high, fill_value=np.nan)
    plusdi = np.full_like(high, fill_value=np.nan)
    minusdi = np.full_like(high, fill_value=np.nan)
    dx = np.full_like(high, fill_value=np.nan)
    
    
    for i in range(len(high)):
        if i == 0:
            pass
        else:
            deltahigh[i] = high[i] - high[i-1] # 更新deltahigh
            deltalow[i] = low[i-1] - low[i] # 更新deltalow
            tr[i] = TrueRange(high[i], low[i], close[i-1]) # 更新truerange
            # 更新 plusdm minusdm
            if (deltahigh[i] < 0 and deltalow[i] < 0) or deltahigh[i] == deltalow[i]:
                plusdm[i] = 0
                minusdm[i] = 0
            elif deltahigh[i] > deltalow[i]:
                plusdm[i] = deltahigh[i]
                minusdm[i] = 0
            elif deltahigh[i] < deltalow[i]:
                plusdm[i] = 0
                minusdm[i] = deltalow[i]
            if i == 1:
                # 更新第一个 adm
                
                admplus[i] = plusdm[i]
                admminus[i] = minusdm[i]
                
                # 更新第一个 atr
                atr[i] = tr[i]
            else:
                # 更新第二个及以后的 adm
                
                admplus[i] = (plusdm[i] + (n-1)*admplus[i-1]) / n
                admminus[i] = (minusdm[i] + (n-1)*admminus[i-1]) / n

                # 更新第二个及以后的 atr
                atr[i] = (tr[i] + (n-1)*atr[i-1]) / n
            # 更新 di
            plusdi[i] = 100 * admplus[i] / atr[i]
            minusdi[i] = 100 * admminus[i] / atr[i]
            # 更新 dx
            dx[i] = DX_inc(plusdi[i], minusdi[i])
            
    return dx

In [89]:
import numpy as np

n_samples = 1000
high = np.random.random(n_samples)
low = np.random.random(n_samples)
close = np.random.random(n_samples)

In [36]:
import talib

talib.DX(high, low, close)

array([        nan,         nan,         nan,         nan,         nan,
               nan,         nan,         nan,         nan,         nan,
               nan,         nan,         nan,         nan, 58.1941225 ,
       36.82349469, 44.19527758, 37.389209  , 37.389209  , 46.22644958,
       35.53719896, 22.19089703, 36.96131321, 36.96131321,  8.60637509,
       11.93747793, 25.48203819,  7.48131543, 12.04634655,  3.91033545,
       16.55344249,  4.20539295,  5.88107473,  6.51908631,  6.51908631,
        2.29477081,  6.17257612,  6.17257612, 13.49677576, 13.49677576,
        6.23449039,  6.23449039,  3.8965676 , 12.87527403, 12.87527403,
       12.87527403,  3.41741259,  9.90034482,  9.90034482,  5.37428342,
        8.61501216,  8.61501216, 12.60975363, 12.60975363, 12.60975363,
        6.59572522,  6.59572522,  6.59572522, 23.41143022, 22.60173964,
       14.55341357,  6.19294231,  6.19294231,  6.19294231, 21.85382993,
       17.00793815, 17.00793815, 17.00793815,  3.8504934 ,  3.85

In [67]:
DX(high, low, close)

array([         nan, 100.        ,  90.51700158,  79.74036145,
        81.69089977,  72.50576844,  72.50576844,  73.16012233,
        57.73148056,  59.84806634,  44.29815607,  44.29815607,
        35.92693387,  37.98555802,  41.09715483,  39.8444081 ,
        44.98628422,  29.07581704,  29.07581704,  31.81953951,
        12.66540091,  20.64843863,  20.64843863,  28.28634652,
        28.28634652,  13.96252481,  13.96252481,   7.35404518,
        10.99413453,  21.0851502 ,  13.35418588,  10.75201377,
        12.70148134,  12.70148134,  11.80100279,  21.46497975,
        26.13196024,  31.47482724,  31.22037347,  10.78500472,
        10.78500472,   5.33717036,   6.5127242 ,   4.62424062,
        16.02571616,  16.02571616,   2.9569081 ,  21.36320597,
        15.67918333,  15.67918333,   1.92648583,   8.25347352,
         8.25347352,   5.31535689,   5.46515078,   8.18939582,
        13.04971246,  10.5507759 ,   6.15774137,  23.32671966,
        17.69625608,  11.87143807,  21.43476706,   4.57

In [68]:
talib.DX(high, low, close)

array([        nan,         nan,         nan,         nan,         nan,
               nan,         nan,         nan,         nan,         nan,
               nan,         nan,         nan,         nan, 36.7308464 ,
       25.81477017, 26.72875313, 26.72875313, 32.32737061, 36.13907661,
       19.96304815, 34.28110786, 20.27825212, 20.27825212,  2.55277077,
        2.55277077,  1.26071379,  1.26071379, 16.59016191, 16.59016191,
       14.44187356, 12.50773075, 25.60703832, 11.26365909,  2.65042823,
        2.65042823,  2.65042823,  5.53449618,  6.0874489 ,  6.0874489 ,
        9.20603662,  9.20603662,  4.47897828, 14.90806626, 14.83604313,
       22.75346684, 29.69879545, 13.30214624, 20.1683155 , 12.2284401 ,
       12.2284401 , 12.2284401 , 30.48761659, 30.48761659, 12.1112146 ,
        5.73755604, 17.61528065,  5.28050405,  3.98803519,  8.80091484,
        8.84358777, 11.22085341,  2.27302002,  2.27302002,  6.74564693,
        8.34625002,  5.72446727,  6.75757061,  9.90046018,  9.90

In [93]:
DX(high, low, close) - talib.DX(high, low, close)

array([         nan,          nan,          nan,          nan,
                nan,          nan,          nan,          nan,
                nan,          nan,          nan,          nan,
                nan,          nan, -35.13821937, -35.13821937,
       -34.14835112, -31.54357409, -31.54357409, -26.04252645,
       -26.04252645, -24.6304144 , -23.39140875, -23.39140875,
         1.79759302,   0.52320695,  13.42487699,  13.42487699,
         1.41610796, -15.12903006,  10.82693431,  -5.0475226 ,
        -5.0475226 ,   9.95256415,   9.95256415,  -8.18480134,
         7.19968591,  -6.07226988,   5.32530463,   5.27580335,
         4.78039336,   0.91861066,   4.64855131,  -0.20118003,
         4.12365811,   4.12365811,   1.11828117,   1.11828117,
         3.23202274,   0.18146292,   2.31063706,   2.10298642,
         2.10298642,   2.05274585,   1.93107331,   1.92077336,
         1.82280657,   1.63107382,   1.52189768,   1.46426506,
         1.37539876,   1.30803649,   1.18185196,   1.17