https://github.com/Khushali26/MoneyFlowIndexCalculations/blob/master/money_flow_index.ipynb

In [1]:
import numpy as np
from scipy.ndimage.interpolation import shift



inputs = {
    'open': np.random.random(100),
    'high': np.random.random(100),
    'low': np.random.random(100),
    'close': np.random.random(100),
    'volume': np.random.random(100)
}

In [2]:
high = inputs['high']
low = inputs['low']
close = inputs['close']
vol = inputs['volume']

typicalPrice = (high + low + close)/3
preTypicalPrice = shift(typicalPrice, 1, cval=np.nan)

moneyFlow = typicalPrice * vol
pmf = np.zeros_like(high)
pmf[0] = np.nan
nmf = np.zeros_like(high)
nmf[0] = np.nan

condition1 = typicalPrice > preTypicalPrice
pmf[condition1] = moneyFlow[condition1]
condition2 = typicalPrice <= preTypicalPrice
nmf[condition2] = moneyFlow[condition2]

/opt/anaconda3/lib/python3.6/site-packages/ipykernel/__main__.py:15: RuntimeWarning: invalid value encountered in greater
/opt/anaconda3/lib/python3.6/site-packages/ipykernel/__main__.py:17: RuntimeWarning: invalid value encountered in less_equal


In [4]:

pmf

array([       nan, 0.15716184, 0.        , 0.        , 0.10457107,
       0.        , 0.46089382, 0.        , 0.        , 0.        ,
       0.16167614, 0.37231559, 0.        , 0.        , 0.14262733,
       0.5506388 , 0.        , 0.23031477, 0.2585752 , 0.        ,
       0.3962347 , 0.        , 0.36313305, 0.        , 0.26836878,
       0.06924511, 0.        , 0.        , 0.20255638, 0.        ,
       0.3307599 , 0.        , 0.        , 0.85093446, 0.        ,
       0.06037494, 0.        , 0.06212197, 0.        , 0.01523911,
       0.08626247, 0.        , 0.23423719, 0.45140705, 0.        ,
       0.36537035, 0.23452018, 0.        , 0.02291061, 0.08941765,
       0.14852839, 0.        , 0.        , 0.        , 0.19168411,
       0.        , 0.        , 0.28533648, 0.        , 0.54357631,
       0.        , 0.        , 0.17377461, 0.        , 0.40395966,
       0.        , 0.3998375 , 0.02868262, 0.        , 0.00442338,
       0.        , 0.24738827, 0.        , 0.30344049, 0.43155

In [14]:

pmfs = np.full_like(pmf, np.nan)
nmfs = np.full_like(nmf, np.nan)
n = 5
i = 0
set_first_pmfs = False
set_first_nmfs = False
while (i+n) <= len(pmf):
    if not set_first_pmfs:
        pmfs[i+n-1] = pmf[i:i+n].sum(where=np.invert(np.isnan(pmf[i:i+n])))
        
        set_first_pmfs = True
    else:
        if np.isnan(pmf[i-1]):
            prePmf = 0
        else:
            prePmf = pmf[i-1]
            
        nextPmf = pmf[i+n-1]
            
        pmfs[i+n-1] = pmfs[i+n-2] - prePmf + nextPmf
 
    if not set_first_nmfs:
        nmfs[i+n-1] = nmf[i:i+n].sum(where=np.invert(np.isnan(nmf[i:i+n])))
        set_first_nmfs = True
    else:
        if np.isnan(nmf[i-1]):
            preNmf = 0
        else:
            preNmf = nmf[i-1]    
            
        nextNmf = nmf[i+n-1]
            
        nmfs[i+n-1] = nmfs[i+n-2] - preNmf + nextNmf
        
    i+=1
    

In [15]:
pmfs

array([       nan,        nan,        nan,        nan, 0.26173291,
       0.26173291, 0.56546488, 0.56546488, 0.56546488, 0.46089382,
       0.62256995, 0.53399173, 0.53399173, 0.53399173, 0.67661906,
       1.06558172, 0.69326613, 0.9235809 , 1.1821561 , 1.03952877,
       0.88512468, 0.88512468, 1.01794295, 0.75936775, 1.02773654,
       0.70074695, 0.70074695, 0.3376139 , 0.54017028, 0.2718015 ,
       0.53331629, 0.53331629, 0.53331629, 1.18169436, 1.18169436,
       0.9113094 , 0.9113094 , 0.97343137, 0.12249692, 0.13773603,
       0.16362356, 0.16362356, 0.33573878, 0.78714583, 0.77190672,
       1.05101459, 1.28553478, 1.05129758, 0.62280114, 0.7122188 ,
       0.49537683, 0.26085665, 0.26085665, 0.23794604, 0.34021249,
       0.19168411, 0.19168411, 0.47702059, 0.47702059, 0.8289128 ,
       0.8289128 , 0.8289128 , 0.71735093, 0.71735093, 0.57773427,
       0.57773427, 0.97757176, 0.83247978, 0.83247978, 0.4329435 ,
       0.4329435 , 0.28049427, 0.25181165, 0.55525214, 0.98238

In [16]:
nmfs

array([       nan,        nan,        nan,        nan, 0.429639  ,
       0.87838474, 0.87838474, 0.87908791, 0.80367259, 0.99004029,
       0.54129454, 0.54129454, 0.27524045, 0.51774283, 0.33137513,
       0.33137513, 0.34652551, 0.33731017, 0.01515039, 0.15939287,
       0.15939287, 0.15367846, 0.15367846, 0.31295614, 0.16871366,
       0.16871366, 0.63470815, 0.6432391 , 0.48396141, 0.54185394,
       0.54185394, 0.36011219, 0.57202711, 0.57202711, 0.90760685,
       0.90760685, 0.9915904 , 0.77114453, 0.95792654, 0.56445427,
       0.56445427, 0.39845353, 0.39845353, 0.21167153, 0.39262219,
       0.39262219, 0.18095066, 0.2691224 , 0.2691224 , 0.08817174,
       0.08817174, 0.62171619, 0.73343977, 0.77162028, 0.77162028,
       0.82505676, 0.66828413, 0.4683888 , 0.69989571, 0.69989571,
       1.04195357, 0.9773603 , 0.9773603 , 0.7828179 , 0.7828179 ,
       0.56032784, 0.24814929, 0.24814929, 0.32957471, 0.32957471,
       0.46162852, 0.46162852, 0.66861967, 0.51204924, 0.51204

In [18]:
moneyRatio = pmfs/nmfs
moneyRatio

array([        nan,         nan,         nan,         nan,  0.60919262,
        0.29797069,  0.64375536,  0.64324043,  0.70360106,  0.46553036,
        1.15015006,  0.98650861,  1.94009179,  1.03138412,  2.04185228,
        3.21563578,  2.00062074,  2.73807607, 78.02812106,  6.52180206,
        5.55310069,  5.75958853,  6.6238494 ,  2.42643504,  6.09160257,
        4.15346907,  1.10404593,  0.52486532,  1.11614329,  0.50161396,
        0.98424363,  1.48097258,  0.93232694,  2.06580132,  1.30198924,
        1.00407946,  0.91903814,  1.26232027,  0.12787715,  0.24401628,
        0.28987921,  0.41064653,  0.8426046 ,  3.71871384,  1.96602929,
        2.67691086,  7.10433868,  3.90639199,  2.31419289,  8.07763132,
        5.61831762,  0.41957513,  0.35566199,  0.30837194,  0.44090663,
        0.23232839,  0.28683026,  1.01842868,  0.68155953,  1.18433759,
        0.79553717,  0.84811384,  0.73396774,  0.91637011,  0.73801872,
        1.03106471,  3.93945023,  3.35475386,  2.52592127,  1.31

In [20]:
mfi = 100 - 100/(1+moneyRatio)
mfi

array([        nan,         nan,         nan,         nan, 37.85703559,
       22.95665798, 39.16369633, 39.14463248, 41.30081121, 31.76531688,
       53.49161817, 49.66042463, 65.98745645, 50.77248125, 67.12529379,
       76.27878566, 66.67356231, 73.24827049, 98.73462764, 86.70531355,
       84.7400483 , 85.20620012, 86.88326661, 70.81514785, 85.89881497,
       80.59559518, 52.47252042, 34.42043794, 52.74422075, 33.40498758,
       49.60296274, 59.69322649, 48.24892319, 67.38210026, 56.55931051,
       50.10177891, 47.8905615 , 55.79759355, 11.33786151, 19.61519961,
       22.4733612 , 29.11051927, 45.72899686, 78.80778461, 66.28489125,
       72.8032569 , 87.66093027, 79.61842424, 69.8267411 , 88.9839104 ,
       84.89041994, 29.55638763, 26.23529996, 23.56913413, 30.59925033,
       18.85279871, 22.28967306, 50.4565105 , 40.53139472, 54.21953063,
       44.30636054, 45.89077908, 42.32880004, 47.81801303, 42.46322052,
       50.76473965, 79.75483194, 77.03658959, 71.63861803, 56.77

In [30]:
def MFI_inc(MoneyRatio):
    return 100 - (100/(1+MoneyRatio))

def MFI(high, low, close, vol, n=14):
    typical_price = np.full_like(high, fill_value=np.nan)
    money_flow = np.full_like(high, fill_value=np.nan)
    positive_money_flow = np.full_like(high, fill_value=np.nan)
    negative_money_flow = np.full_like(high, fill_value=np.nan)
    money_ratio = np.full_like(high, fill_value=np.nan)
    mfi = np.full_like(high, fill_value=np.nan)
    
    for i in range(len(high)):
        # 更新 typicalprice, moneyflow
        typical_price[i] = (high[i] + low[i] + close[i]) / 3
        money_flow[i] = typical_price[i] * vol[i]
        
        if i == 0:
            pass
        else:
            # 更新 positivemoneyflow, negativemoneyflow
            if typical_price[i] > typical_price[i-1]:
                positive_money_flow[i] = money_flow[i]
                negative_money_flow[i] = 0
            else:
                positive_money_flow[i] = 0
                negative_money_flow[i] = money_flow[i]
                
            # 更新 moneyratio
            if i >= n:
                money_ratio[i] = positive_money_flow[i-n+1:i+1].sum() / negative_money_flow[i-n+1:i+1].sum()
                # 更新 moneyflowindex
                mfi[i] = MFI_inc(money_ratio[i])
                                
    return mfi
            
    

In [24]:
import numpy as np
import talib

high = np.random.random(100)
low = np.random.random(100)
close = np.random.random(100)
vol = np.random.random(100)

In [32]:
MFI(high, low, close, vol) - talib.MFI(high, low, close, vol)

array([           nan,            nan,            nan,            nan,
                  nan,            nan,            nan,            nan,
                  nan,            nan,            nan,            nan,
                  nan,            nan, 0.00000000e+00, 0.00000000e+00,
       7.10542736e-15, 7.10542736e-15, 7.10542736e-15, 2.13162821e-14,
       1.42108547e-14, 1.42108547e-14, 2.13162821e-14, 2.84217094e-14,
       1.42108547e-14, 1.42108547e-14, 2.84217094e-14, 1.42108547e-14,
       2.13162821e-14, 2.13162821e-14, 2.13162821e-14, 2.13162821e-14,
       2.13162821e-14, 7.10542736e-15, 1.42108547e-14, 1.42108547e-14,
       7.10542736e-15, 7.10542736e-15, 1.42108547e-14, 7.10542736e-15,
       0.00000000e+00, 7.10542736e-15, 2.13162821e-14, 1.42108547e-14,
       7.10542736e-15, 1.42108547e-14, 1.42108547e-14, 1.42108547e-14,
       2.84217094e-14, 1.42108547e-14, 1.42108547e-14, 0.00000000e+00,
       1.42108547e-14, 1.42108547e-14, 0.00000000e+00, 1.42108547e-14,
      

In [27]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [28]:
a[0:3]

array([0, 1, 2])