In [2]:
import numpy as np

In [110]:
def NATR_inc(close, atr):
    
    natr = 100*atr/close
    return natr

def ATR_inc(TR, preATR, n):
    return (TR + preATR*(n-1))/n
    

def trueRange_inc(preClose, high, low):
    return max([high-low,abs(high-preClose),abs(low-preClose)])
    
def NATR(high, low, close, n=14):
    tr = np.full_like(high, fill_value=np.nan)
    atr = np.full_like(high, fill_value=np.nan)
    natr = np.full_like(high, fill_value=np.nan)
    
    for i in range(len(high)):
        if i == 0:
            pass
        else:
            tr[i] = trueRange_inc(close[i-1], high[i], low[i])
            if i == 1:
                atr[i] = tr[i]
            elif i >= 2:
                atr[i] = ATR_inc(tr[i], atr[i-1], n)
                natr[i] = NATR_inc(close[i], atr[i])
            
    return natr

def ATR(high, low, close, n=14):
    tr = np.full_like(high, fill_value=np.nan)
    atr = np.full_like(high, fill_value=np.nan)
    
    for i in range(len(high)):
        if i == 0:
            pass
        else:
            tr[i] = trueRange_inc(close[i-1], high[i], low[i])
            if i == 1:
                atr[i] = tr[i]
            elif i >= 2:
                atr[i] = ATR_inc(tr[i], atr[i-1], n)
                
    return atr
                
            

In [106]:
import numpy as np

high = np.random.random(1000)*1000
low = np.random.random(1000)*1000
close = np.random.random(1000)*1000

In [111]:
import talib

NATR(high, low, close) - talib.NATR(high, low, close)

array([            nan,             nan,             nan,             nan,
                   nan,             nan,             nan,             nan,
                   nan,             nan,             nan,             nan,
                   nan,             nan,  1.57408783e+01,  5.49533159e+01,
        1.07463520e+01,  4.75366045e+03,  1.10712968e+02,  8.80254990e+00,
        1.15501746e+01,  1.15015324e+01,  7.70238146e+00,  2.44900247e+01,
        2.52312245e+01,  3.94300287e+01,  1.13941653e+01,  1.07019005e+01,
        1.44593912e+01,  3.39758461e+01,  5.44905533e+00,  7.07648787e+00,
        2.04962324e+02,  2.86524735e+01,  4.33430790e+00,  7.10191719e+00,
        4.50486522e+00,  3.12629806e+00,  5.61812013e+00,  8.33762099e+00,
        4.01047791e+00,  6.82991572e+00,  1.54829282e+00,  9.15109991e+00,
        1.73739872e+01,  1.96811385e+01,  4.45215105e+00,  1.67841840e+00,
        2.57569454e+00,  1.17854092e+00,  8.48121940e-01,  8.80494611e+00,
        2.03072563e+00,  

array([         nan,          nan,          nan,          nan,
                nan,          nan,          nan,          nan,
                nan,          nan,          nan,          nan,
                nan,          nan, 387.3100168 , 398.32017822,
       436.35606566, 465.98075738, 452.94283332, 465.10684001,
       468.92667724, 492.68507752, 489.85592141, 470.87678187,
       476.04401079, 457.62846943, 460.98514025, 447.05851773,
       472.8333546 , 485.84475604, 457.9416279 , 475.18617792,
       495.4640483 , 498.88608741, 516.21624702, 510.77214206,
       489.15446432, 477.18868765, 468.51325742, 442.87695005,
       459.19598551, 460.06426009, 471.34021145, 500.04572458,
       483.39451578, 482.36501218, 477.75455522, 498.25276635,
       524.41752288, 517.85338158, 514.63501241, 493.68596167,
       464.48069673, 481.68093914, 461.92011566, 457.0584936 ,
       433.92821073, 425.89408626, 444.06682307, 473.6218911 ,
       472.64115211, 463.23874372, 449.7579148 , 461.07

In [12]:
NATR(high, low, close)

array([          nan,           nan,  112.58130877,  116.34813135,
         42.77245043,  106.19316676,  418.04980699,  182.33068699,
          8.68927104,  603.54115535,  102.35259318, 1697.85770074,
        250.91458321,  684.65528135,   70.98284693,  733.43382567,
         32.55225936,  111.45579938,  195.78259624,  158.22309076,
        114.48982286,   50.37022222,   47.2540685 ,   31.35578359,
        203.27508556,  100.99191262,   45.25876106,   17.33297338,
         41.53709698,  407.0637383 ,   33.22394486,   22.42762175,
        107.64652018,  130.64738743,   80.83603672,  101.66732236,
        114.73162112,   86.40678555,  135.99674456,   19.81380272,
        241.86084867,  358.11589523,  223.2661374 ,   30.85667364,
         83.7155443 ,   24.63272934,  103.2002357 , 1670.52969797,
        215.19367599,  135.5023945 ,  101.48852896, 1140.52381468,
        131.78472266,  137.03897632,  877.66277109,   26.15587248,
        361.27315744,  298.94143168,  115.16473825,   55.92752

In [14]:
NATR(high, low, close)

array([          nan,           nan,  112.58130877,  116.34813135,
         42.77245043,  106.19316676,  418.04980699,  182.33068699,
          8.68927104,  603.54115535,  102.35259318, 1697.85770074,
        250.91458321,  684.65528135,   70.98284693,  733.43382567,
         32.55225936,  111.45579938,  195.78259624,  158.22309076,
        114.48982286,   50.37022222,   47.2540685 ,   31.35578359,
        203.27508556,  100.99191262,   45.25876106,   17.33297338,
         41.53709698,  407.0637383 ,   33.22394486,   22.42762175,
        107.64652018,  130.64738743,   80.83603672,  101.66732236,
        114.73162112,   86.40678555,  135.99674456,   19.81380272,
        241.86084867,  358.11589523,  223.2661374 ,   30.85667364,
         83.7155443 ,   24.63272934,  103.2002357 , 1670.52969797,
        215.19367599,  135.5023945 ,  101.48852896, 1140.52381468,
        131.78472266,  137.03897632,  877.66277109,   26.15587248,
        361.27315744,  298.94143168,  115.16473825,   55.92752

In [69]:
talib.TRANGE(high, low, close) - TRANGE(high, low, close)

array([nan,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [68]:
def TRANGE(high, low, close):
    
    tr = np.full_like(high, fill_value=np.nan)
    
    for i in range(len(high)):
        if i == 0:
            pass
        else:
            tr[i] = trueRange_inc(close[i-1], high[i], low[i])
            
    return tr

In [67]:
talib.TRANGE(high, low, close)

array([         nan, 382.97917057, 613.41578132, 622.92648782,
       716.64856972, 845.54027602, 488.14080593, 543.850363  ,
       872.59264229, 153.27110075, 294.87403496, 601.63506258,
       466.4083083 , 356.76365573, 358.05367042, 494.05247786,
        98.88767986, 507.5213808 , 943.64668546, 393.09572595,
       137.99117678, 741.49054043, 807.61392145, 365.11878395,
       491.03474107, 658.13193213, 659.20961348, 724.2874492 ,
       856.54088235, 447.19818979, 205.08787756,  97.69014409,
        67.91673924,  16.64241412, 996.37176169, 124.67142839,
       476.57215734, 368.75214462, 572.13900163, 178.98777031,
       293.04239808, 229.02366145, 366.26916468,  69.83981712,
       657.46310635, 697.68943964, 416.79853189, 113.18065352,
       679.66633735, 107.31631235, 875.59307292, 561.88636087,
       519.11705089, 419.09102247, 483.1280376 , 572.79319495,
       354.08603239, 521.79444402, 265.95423626, 758.15733627,
       328.84425871, 619.44910774, 320.79900597, 547.25

In [66]:
TRANGE(high, low, close)

array([         nan, 382.97917057, 613.41578132, 622.92648782,
       716.64856972, 845.54027602, 488.14080593, 543.850363  ,
       872.59264229, 153.27110075, 294.87403496, 601.63506258,
       466.4083083 , 356.76365573, 358.05367042, 494.05247786,
        98.88767986, 507.5213808 , 943.64668546, 393.09572595,
       137.99117678, 741.49054043, 807.61392145, 365.11878395,
       491.03474107, 658.13193213, 659.20961348, 724.2874492 ,
       856.54088235, 447.19818979, 205.08787756,  97.69014409,
        67.91673924,  16.64241412, 996.37176169, 124.67142839,
       476.57215734, 368.75214462, 572.13900163, 178.98777031,
       293.04239808, 229.02366145, 366.26916468,  69.83981712,
       657.46310635, 697.68943964, 416.79853189, 113.18065352,
       679.66633735, 107.31631235, 875.59307292, 561.88636087,
       519.11705089, 419.09102247, 483.1280376 , 572.79319495,
       354.08603239, 521.79444402, 265.95423626, 758.15733627,
       328.84425871, 619.44910774, 320.79900597, 547.25

In [65]:
talib.TRANGE(high, low, close) - TRANGE(high, low, close)

array([nan,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])