In [11]:
def PLUS_DM_inc(high, prehigh, low, prelow, pre_plus_dm_n, n):
    plusdm, _ = dm_one_period(high, prehigh, low, prelow)
        
    plus_dm_n = pre_plus_dm_n - pre_plus_dm_n/n + plusdm
    
    return plus_dm_n

def dm_one_period(high, prehigh, low, prelow):
    deltahigh = high - prehigh
    deltalow = prelow - low
    
    if (deltahigh < 0 and deltalow < 0) or deltahigh == deltalow:
        plusdm = 0
        minusdm = 0
    elif deltahigh > deltalow:
        plusdm = deltahigh
        minusdm = 0
    elif deltahigh < deltalow:
        plusdm = 0
        minusdm = deltalow
    else:
        raise ExceptionError
        
    return plusdm, minusdm

def PLUS_DM(high, low, n=14):
    plus_dm = np.full_like(high, fill_value=np.nan)
    init_plusdm = 0
    
    for i in range(len(high)):
        if i == 0:
            pass
        elif i < n:
            init_plusdm += dm_one_period(high[i], high[i-1], low[i], low[i])[0]
            if i == n-1:
                plus_dm[i] = init_plusdm
        else:
            plus_dm[i] = PLUS_DM_inc(high[i], high[i-1], low[i], low[i-1], plus_dm[i-1], n)
            
    return plus_dm
            
            

In [23]:
import numpy as np
import talib

high = np.random.random(200)*100
low = np.random.random(200)*100



In [25]:
talib.PLUS_DM(high, low,14) - PLUS_DM(high, low, 14)

array([            nan,             nan,             nan,             nan,
                   nan,             nan,             nan,             nan,
                   nan,             nan,             nan,             nan,
                   nan, -1.75011332e+00, -1.62510522e+00, -1.50902628e+00,
       -1.40123869e+00, -1.30115021e+00, -1.20821091e+00, -1.12191013e+00,
       -1.04177369e+00, -9.67361286e-01, -8.98264051e-01, -8.34102333e-01,
       -7.74523595e-01, -7.19200481e-01, -6.67829018e-01, -6.20126945e-01,
       -5.75832164e-01, -5.34701295e-01, -4.96508345e-01, -4.61043463e-01,
       -4.28111787e-01, -3.97532374e-01, -3.69137204e-01, -3.42770261e-01,
       -3.18286671e-01, -2.95551909e-01, -2.74441058e-01, -2.54838126e-01,
       -2.36635402e-01, -2.19732874e-01, -2.04037668e-01, -1.89463549e-01,
       -1.75930438e-01, -1.63363979e-01, -1.51695123e-01, -1.40859757e-01,
       -1.30798346e-01, -1.21455607e-01, -1.12780206e-01, -1.04724477e-01,
       -9.72441575e-02, -

In [21]:
talib.PLUS_DM(high, low,14)

array([         nan,          nan,          nan,          nan,
                nan,          nan,          nan,          nan,
                nan,          nan,          nan,          nan,
                nan, 150.78790106, 140.01733669, 163.31321292,
       151.64798342, 140.81598461, 213.31503281, 198.07824475,
       241.27790773, 224.04377147, 208.04064493, 193.18059887,
       179.38198466, 262.2795607 , 243.54530636, 229.37345654,
       212.98963821, 197.77609262, 183.64922887, 233.78163618,
       217.08294788, 204.20263731, 189.61673464, 201.6600604 ,
       187.25577037, 173.8803582 , 161.46033261, 149.92745171,
       139.21834802, 129.2741803 , 198.02886238, 187.75346655,
       174.34250465, 161.8894686 , 150.32593513, 158.01498784,
       160.01651437, 184.73178318, 171.53665581, 159.28403753,
       217.30306602, 201.78141844, 187.36845998, 235.03725382,
       218.24887855, 202.65967294, 197.91787635, 208.26705036,
       193.39083248, 179.57720159, 166.75025862, 207.74

In [20]:
PLUS_DM(high, low, 14)

array([         nan,          nan,          nan,          nan,
                nan,          nan,          nan,          nan,
                nan,          nan,          nan,          nan,
                nan, 157.51968918, 146.26828281, 169.11766289,
       157.03782982, 145.82084198, 217.96240037, 202.39365748,
       245.2850767 , 227.76471408, 211.49580593, 196.38896265,
       182.3611796 , 265.045956  , 246.114102  , 231.75876677,
       215.20456914, 199.8328142 , 185.55904176, 235.55503387,
       218.72967431, 205.73174041, 191.0366161 , 202.97852175,
       188.48005591, 175.01719478, 162.51596658, 150.90768325,
       140.12856302, 130.11937995, 198.81369062, 188.48223563,
       175.01921879, 162.51784602, 150.90942845, 158.55680307,
       160.51962851, 185.19896059, 171.9704634 , 159.68685887,
       217.6771144 , 202.12874909, 187.6909813 , 235.3367379 ,
       218.52697091, 202.91790156, 198.15766006, 208.48970667,
       193.59758477, 179.76918585, 166.92852972, 207.90