In [27]:
def trueRange_inc(preClose, high, low):
    return max([high-low,abs(high-preClose),abs(low-preClose)])

def true_range_n_inc(pre_true_range_n, preClose, high, low, n):
    tr = trueRange_inc(preClose, high, low)
    true_range_n = pre_true_range_n - pre_true_range_n / n + tr
    return true_range_n

def PLUS_DM_inc(high, prehigh, low, prelow, pre_plus_dm_n, n):
    plusdm, _ = dm_one_period(high, prehigh, low, prelow)
        
    plus_dm_n = pre_plus_dm_n - pre_plus_dm_n/n + plusdm
    
    return plus_dm_n

def dm_one_period(high, prehigh, low, prelow):
    deltahigh = high - prehigh
    deltalow = prelow - low
    
    if (deltahigh < 0 and deltalow < 0) or deltahigh == deltalow:
        plusdm = 0
        minusdm = 0
    elif deltahigh > deltalow:
        plusdm = deltahigh
        minusdm = 0
    elif deltahigh < deltalow:
        plusdm = 0
        minusdm = deltalow
    else:
        raise ExceptionError
        
    return plusdm, minusdm

def PLUS_DI_inc(plus_dm_n, true_range_n):
    return plus_dm_n / true_range_n * 100

def PLUS_DI(high, low, close, n=14):
    plus_dm = np.full_like(high, fill_value=np.nan)
    true_range_n = np.full_like(high, fill_value=np.nan)
    plus_di = np.full_like(high, fill_value=np.nan)
    init_plusdm = 0
    init_true_range_n = 0
    
    for i in range(len(high)):
        if i == 0:
            pass
        elif i < n:
            init_plusdm += dm_one_period(high[i], high[i-1], low[i], low[i])[0]
            init_true_range_n += trueRange_inc(close[i-1], high[i], low[i])
            if i == n-1:
                plus_dm[i] = init_plusdm
                true_range_n[i] = init_true_range_n
                plus_di[i] = PLUS_DI_inc(plus_dm[i], true_range_n[i])
        else:
            plus_dm[i] = PLUS_DM_inc(high[i], high[i-1], low[i], low[i-1], plus_dm[i-1], n)
            true_range_n[i] = true_range_n_inc(true_range_n[i-1], close[i-1], high[i], low[i], n)
            plus_di[i] = PLUS_DI_inc(plus_dm[i], true_range_n[i])
            
    return plus_di
            
            

In [22]:
import numpy as np

size = 100
high = np.random.random(size)
low = np.random.random(size)
close = np.random.random(size)

In [26]:
import talib

PLUS_DI(high, low, close) - talib.PLUS_DI(high, low, close)

array([nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [24]:
PLUS_DI(high, low, close)

array([        nan,         nan,         nan,         nan,         nan,
               nan,         nan,         nan,         nan,         nan,
               nan,         nan,         nan, 32.42948781, 30.26720826,
       31.6243857 , 28.36257342, 27.38834522, 25.34628334, 24.20296863,
       24.79876593, 23.03717174, 24.43277816, 21.65802369, 29.44613491,
       27.10052854, 24.88114341, 24.53214714, 24.18678095, 28.29442641,
       28.06613627, 25.82126288, 27.36034034, 24.52117724, 28.93045526,
       27.33166514, 26.29016675, 23.72936426, 29.39939081, 26.3981342 ,
       24.93990103, 32.14110149, 30.52730819, 28.87390823, 33.71557407,
       32.771985  , 36.40795796, 34.27196166, 33.15265169, 34.97017976,
       33.85266265, 30.65161216, 27.88483928, 27.00244388, 30.82090549,
       27.18264555, 34.56320823, 33.54600475, 32.00647335, 29.37631729,
       27.38539419, 24.42934647, 31.92548998, 28.2339292 , 26.98752733,
       36.15151681, 32.47222265, 37.65478434, 35.72885813, 34.65

In [25]:
talib.PLUS_DI(high, low, close)

array([        nan,         nan,         nan,         nan,         nan,
               nan,         nan,         nan,         nan,         nan,
               nan,         nan,         nan,         nan, 30.26720826,
       31.6243857 , 28.36257342, 27.38834522, 25.34628334, 24.20296863,
       24.79876593, 23.03717174, 24.43277816, 21.65802369, 29.44613491,
       27.10052854, 24.88114341, 24.53214714, 24.18678095, 28.29442641,
       28.06613627, 25.82126288, 27.36034034, 24.52117724, 28.93045526,
       27.33166514, 26.29016675, 23.72936426, 29.39939081, 26.3981342 ,
       24.93990103, 32.14110149, 30.52730819, 28.87390823, 33.71557407,
       32.771985  , 36.40795796, 34.27196166, 33.15265169, 34.97017976,
       33.85266265, 30.65161216, 27.88483928, 27.00244388, 30.82090549,
       27.18264555, 34.56320823, 33.54600475, 32.00647335, 29.37631729,
       27.38539419, 24.42934647, 31.92548998, 28.2339292 , 26.98752733,
       36.15151681, 32.47222265, 37.65478434, 35.72885813, 34.65