In [4]:
class TAHelper:
    def __init__(self):
        self.i=-1
        self.length = 10000
        self.high = np.full(self.length, fill_value=np.nan)
        self.low = np.full(self.length, fill_value=np.nan)
        self.close = np.full(self.length, fill_value=np.nan)
        self.vol = np.full(self.length, fill_value=np.nan)
        
        # 计算DX需要的变量
        self.dx_n = 14
        self.deltahigh = np.full(self.length, fill_value=np.nan)
        self.deltalow = np.full(self.length, fill_value=np.nan)
        self.plusdm = np.full(self.length, fill_value=np.nan)
        self.minusdm = np.full(self.length, fill_value=np.nan)
        self.admplus = np.full(self.length, fill_value=np.nan)
        self.admminus = np.full(self.length, fill_value=np.nan)
        self.tr = np.full(self.length, fill_value=np.nan)
        self.dx_atr = np.full(self.length, fill_value=np.nan)
        self.plusdi = np.full(self.length, fill_value=np.nan)
        self.minusdi = np.full(self.length, fill_value=np.nan)
        self.dx = np.full(self.length, fill_value=np.nan)
        # 计算ADX需要的变量
        self.adx = np.full(self.length, fill_value=np.nan)
        
        # 计算MFI需要的变量
        self.mfi_n = 14
        self.typical_price = np.full(self.length, fill_value=np.nan)
        self.money_flow = np.full(self.length, fill_value=np.nan)
        self.positive_money_flow = np.full(self.length, fill_value=np.nan)
        self.negative_money_flow = np.full(self.length, fill_value=np.nan)
        self.money_ratio = np.full(self.length, fill_value=np.nan)
        self.mfi = np.full(self.length, fill_value=np.nan)
        
        # 计算APO需要的变量
        self.apo_fast_n = 12
        self.apo_slow_n = 26
        self.apo_fastma = np.full(self.length, fill_value=np.nan)
        self.apo_slowma = np.full(self.length, fill_value=np.nan)
        self.apo = np.full(self.length, fill_value=np.nan)
        
        # 计算MACD需要的变量
        self.macd_fast_n = 12
        self.macd_slow_n = 26
        self.macd_signal_n = 9
        self.macd_fastema = np.full(self.length, fill_value=np.nan)
        self.macd_slowema = np.full(self.length, fill_value=np.nan)
        self.macd = np.full(self.length, fill_value=np.nan)
        self.macdsignal = np.full(self.length, fill_value=np.nan)
        self.macdhist = np.full(self.length, fill_value=np.nan)
        
        # 计算NATR需要的变量
        self.natr_n = 14
        self.natr_atr = np.full(self.length, fill_value=np.nan)
        self.natr = np.full(self.length, fill_value=np.nan)
        
        # 计算PLUS_DM需要的变量
        self.plus_dm_n = 14
        self.plus_dm = np.full(self.length, fill_value=np.nan)
        self.init_plusdm = 0
        
        # 计算RSI需要的变量
        self.rsi_n = 14
        self.upavg = np.full(self.length, fill_value=np.nan)
        self.dnavg = np.full(self.length, fill_value=np.nan)
        self.rsi = np.full(self.length, fill_value=np.nan)
        
        # 计算TEMA需要的变量
        self.tema_n = 30
        self.tema_ema1 = np.full(self.length, fill_value=np.nan)
        self.tema_ema2 = np.full(self.length, fill_value=np.nan)
        self.tema_ema3 = np.full(self.length, fill_value=np.nan)
        self.tema = np.full(self.length, fill_value=np.nan)
        
        # 计算自定义指标1需要的变量
        self.customized_indicator_n = 30
        self.customized_indicator = np.full(self.length, fill_value=np.nan)
        self.customized_indicator_max_part = np.full(self.length, fill_value=np.nan)
        self.customized_indicator_abs_part = np.full(self.length, fill_value=np.nan)
        self.customized_indicator_sma_max_part = np.full(self.length, fill_value=np.nan)
        self.customized_indicator_sma_abs_part = np.full(self.length, fill_value=np.nan)
        
        # 计算CCI需要的变量
        self.cci_n = 14
        self.avg_typical_price = np.full(self.length, fill_value=np.nan)
        self.mean_deviation = np.full(self.length, fill_value=np.nan)
        self.cci = np.full(self.length, fill_value=np.nan)
        
        # 计算KDJ需要的变量
        self.kdj_n = 14
        self.k_n = 9
        self.d_n = 9
        self.highest_high = np.full(self.length, fill_value=np.nan)
        self.lowest_low = np.full(self.length, fill_value=np.nan)
        self.rsv = np.full(self.length, fill_value=np.nan)
        self.k = np.full(self.length, fill_value=np.nan)
        self.d = np.full(self.length, fill_value=np.nan)
        self.j = np.full(self.length, fill_value=np.nan)
    
    def TrueRange(self, high, low, preClose):
        return max([high-low, abs(high-preClose), abs(preClose-low)])
    
    def DX_inc(self, plusDI, minusDI):
        return 100 * abs(plusDI - minusDI) / (plusDI + minusDI)
    
    def MFI_inc(self, MoneyRatio):
        return 100 - (100/(1+MoneyRatio))
    
    def APO_inc(self, fastMA, slowMA):    
        return fastMA - slowMA
    
    def MACD_inc(self, fastema, slowema, preSignal, signal_n):
        macd = fastema - slowema
        signal = ((signal_n-1)/(signal_n+1))*preSignal + (2/(signal_n+1))*macd
        hist = macd - signal
        return macd, signal, hist
    
    def NATR_inc(self, close, atr):
        natr = 100*atr/close
        return natr
    
    def dm_one_period(self, high, prehigh, low, prelow):
        deltahigh = high - prehigh
        deltalow = prelow - low

        if (deltahigh < 0 and deltalow < 0) or deltahigh == deltalow:
            plusdm = 0
            minusdm = 0
        elif deltahigh > deltalow:
            plusdm = deltahigh
            minusdm = 0
        elif deltahigh < deltalow:
            plusdm = 0
            minusdm = deltalow
        else:
            raise ExceptionError

        return plusdm, minusdm
    
    def PLUS_DM_inc(self, high, prehigh, low, prelow, pre_plus_dm_n, n):
        plusdm, _ = self.dm_one_period(high, prehigh, low, prelow)
        plus_dm_n = pre_plus_dm_n - pre_plus_dm_n/n + plusdm

        return plus_dm_n
    
    def RSI_inc(self, close, preClose, preUpavg, preDnavg, n=14):
        if close > preClose:
            up = close - preClose
            dn = 0
        else:
            up = 0
            dn = preClose - close

        upavg = (preUpavg*(n-1) + up) / n
        dnavg = (preDnavg*(n-1) + dn) / n
        rsi = 100 * upavg/(upavg + dnavg)

        return rsi
    
    def TEMA_inc(self, ema1, ema2, ema3):
        return 3*ema1 - 3*ema2 + ema3

    def customized_indicator_inc(self, sma_max_part, sma_abs_part):
        return sma_max_part/sma_abs_part*100
    
    def CCI_inc(self, typical_price, avg_typical_price, avg_deviation):
        return (typical_price - avg_typical_price)/(0.015*avg_deviation)
    
    def dx_depends_update(self):
        # DX 依赖变量更新
        # 更新 typicalprice, moneyflow
        self.typical_price[self.i] = (self.high[self.i] + self.low[self.i] + self.close[self.i]) / 3
        self.money_flow[self.i] = self.typical_price[self.i] * self.vol[self.i]
        
        if self.i == 0:
            pass
        else:
            self.deltahigh[self.i] = self.high[self.i] - self.high[self.i-1]
            self.deltalow[self.i] = self.low[self.i-1] - self.low[self.i]
            self.tr[self.i] = self.TrueRange(self.high[self.i], self.low[self.i], self.close[self.i-1])
            # 更新 plusdm minusdm
            if (self.deltahigh[self.i] < 0 and self.deltalow[self.i] < 0) or \
            (self.deltahigh[self.i] == self.deltalow[self.i]):
                self.plusdm[self.i] = 0
                self.minusdm[self.i] = 0
            elif self.deltahigh[self.i] > self.deltalow[self.i]:
                self.plusdm[self.i] = self.deltahigh[self.i]
                self.minusdm[self.i] = 0
            elif self.deltahigh[self.i] < self.deltalow[self.i]:
                self.plusdm[self.i] = 0
                self.minusdm[self.i] = self.deltalow[self.i]
                
            if self.i == 1:
                # 更新第一个 adm
                
                self.admplus[self.i] = self.plusdm[self.i]
                self.admminus[self.i] = self.minusdm[self.i]
                
                # 更新第一个 atr
                self.dx_atr[self.i] = self.tr[self.i]  
            else:
                # 更新第二个及以后的 adm
                
                self.admplus[self.i] = (self.plusdm[self.i] + (self.dx_n-1)*self.admplus[self.i-1]) / self.dx_n
                self.admminus[self.i] = (self.minusdm[self.i] + (self.dx_n-1)*self.admminus[self.i-1]) / self.dx_n

                # 更新第二个及以后的 atr
                self.dx_atr[self.i] = (self.tr[self.i] + (self.dx_n-1)*self.dx_atr[self.i-1]) / self.dx_n
            # 更新 di
            self.plusdi[self.i] = 100 * self.admplus[self.i] / self.dx_atr[self.i]
            self.minusdi[self.i] = 100 * self.admminus[self.i] / self.dx_atr[self.i]
            # 更新 dx
            self.dx[self.i] = self.DX_inc(self.plusdi[self.i], self.minusdi[self.i])
            
            # 更新 adx
            if self.i == 1:
                self.adx[self.i] = self.dx[self.i]
            else:
                self.adx[self.i] = ((self.dx_n-1) * self.adx[self.i-1] + self.dx[self.i]) / self.dx_n
                
    def mfi_depends_update(self):
        # MFI 依赖变量更新
        # 更新 typicalprice, moneyflow
        self.typical_price[self.i] = (self.high[self.i] + self.low[self.i] + self.close[self.i]) / 3
        self.money_flow[self.i] = self.typical_price[self.i] * self.vol[self.i]

        if self.i == 0:
            pass
        else:
            # 更新 positivemoneyflow, negativemoneyflow
            if self.typical_price[self.i] > self.typical_price[self.i-1]:
                self.positive_money_flow[self.i] = self.money_flow[self.i]
                self.negative_money_flow[self.i] = 0
            else:
                self.positive_money_flow[self.i] = 0
                self.negative_money_flow[self.i] = self.money_flow[self.i]

            # 更新 moneyratio
            if self.i >= self.mfi_n:
                self.money_ratio[self.i] = ( self.positive_money_flow[self.i-self.mfi_n+1:self.i+1].sum() /                                                          self.negative_money_flow[self.i-self.mfi_n+1:self.i+1].sum() )
                # 更新 moneyflowindex
                self.mfi[self.i] = self.MFI_inc(self.money_ratio[self.i])
           
    def apo_depends_update(self):
        # APO 依赖变量更新
        # 更新fastma
        if self.i >= self.apo_fast_n-1:
            self.apo_fastma[self.i] = self.close[self.i-self.apo_fast_n+1:self.i+1].mean()
        # 更新slowma
        if self.i >= self.apo_slow_n-1:
            self.apo_slowma[self.i] = self.close[self.i-self.apo_slow_n+1:self.i+1].mean()
            # 更新apo
            self.apo[self.i] = self.APO_inc(self.apo_fastma[self.i], self.apo_slowma[self.i])
            
    def macd_depends_update(self):
        # MACD 依赖变量更新
        # 更新第一个fastema slowema
        if self.i == 0:
            self.macd_fastema[self.i] = self.close[self.i]
            self.macd_slowema[self.i] = self.close[self.i]
            self.macd[self.i] = self.macd_fastema[self.i] - self.macd_slowema[self.i]
            self.macdsignal[self.i] = self.macd[self.i]
            self.macdhist[self.i] = self.macd[self.i] - self.macdsignal[self.i]
        else:
            self.macd_fastema[self.i] = self.macd_fastema[self.i-1]*((self.macd_fast_n-1)/(self.macd_fast_n+1)) + (2/(self.macd_fast_n+1))*self.close[self.i]
            self.macd_slowema[self.i] = self.macd_slowema[self.i-1]*((self.macd_slow_n-1)/(self.macd_slow_n+1)) + (2/(self.macd_slow_n+1))*self.close[self.i]
            self.macd[self.i], self.macdsignal[self.i], self.macdhist[self.i] = self.MACD_inc(self.macd_fastema[self.i], self.macd_slowema[self.i], self.macdsignal[self.i-1], self.macd_signal_n)                
            
    def natr_depends_update(self):
        # NATR 依赖变量更新
        if self.i == 0:
            pass
        else:
            if self.i == 1:
                # 更新第一个natr_atr
                self.natr_atr[self.i] = self.tr[self.i] 
            elif self.i >= 2:
                self.natr_atr[self.i] = (self.tr[self.i] + (self.natr_n-1)*self.natr_atr[self.i-1]) / self.natr_n
                self.natr[self.i] = self.NATR_inc(self.close[self.i], self.natr_atr[self.i])
                
    def plus_dm_depends_update(self):
        # PLUS_DM 依赖变量更新
        if self.i == 0:
            pass
        elif self.i < self.plus_dm_n:
            self.init_plusdm += self.dm_one_period(self.high[self.i], self.high[self.i-1], self.low[self.i], self.low[self.i])[0]
            if self.i == self.plus_dm_n-1:
                self.plus_dm[self.i] = self.init_plusdm
        else:
            self.plus_dm[self.i] = self.PLUS_DM_inc(self.high[self.i], self.high[self.i-1], self.low[self.i], self.low[self.i-1], self.plus_dm[self.i-1], self.plus_dm_n) 
            
    def rsi_depends_update(self):
        # RSI 依赖变量更新
        if self.i == 0:
            pass
        else:
            if self.close[self.i] > self.close[self.i-1]:
                up = self.close[self.i] - self.close[self.i-1]
                dn = 0
            else:
                up = 0
                dn = self.close[self.i-1] - self.close[self.i]
                
            if self.i == 1:
                self.upavg[self.i] = up
                self.dnavg[self.i] = dn
            else:
                self.rsi[self.i] = self.RSI_inc(self.close[self.i], self.close[self.i-1], self.upavg[self.i-1], self.dnavg[self.i-1], self.rsi_n)
                self.upavg[self.i] = ((self.rsi_n-1)*self.upavg[self.i-1] + up) / self.rsi_n
                self.dnavg[self.i] = ((self.rsi_n-1)*self.dnavg[self.i-1] + dn) / self.rsi_n    
 
    def tema_depends_update(self):
        # TEMA 依赖变量更新
        if self.i == 0:
            # 更新第一个ema1 ema2 ema3
            self.tema_ema1[self.i] = self.close[self.i]
            self.tema_ema2[self.i] = self.tema_ema1[self.i]
            self.tema_ema3[self.i] = self.tema_ema2[self.i]
        else:
            self.tema_ema1[self.i] = ((self.tema_n-1)/(self.tema_n+1))*self.tema_ema1[self.i-1] + (2/(self.tema_n+1))*self.close[self.i]
            self.tema_ema2[self.i] = ((self.tema_n-1)/(self.tema_n+1))*self.tema_ema2[self.i-1] + (2/(self.tema_n+1))*self.tema_ema1[self.i]
            self.tema_ema3[self.i] = ((self.tema_n-1)/(self.tema_n+1))*self.tema_ema3[self.i-1] + (2/(self.tema_n+1))*self.tema_ema2[self.i]
            
        self.tema[self.i] = self.TEMA_inc(self.tema_ema1[self.i], self.tema_ema2[self.i], self.tema_ema3[self.i])  
          
    def customized_indicator_depends_update(self):
        # 自定义指标 依赖变量更新
        if self.i == 0:
            pass
        else:
            vol_inc = self.vol[self.i] - self.vol[self.i-1]
            self.customized_indicator_max_part[self.i] = max(vol_inc, 0)
            self.customized_indicator_abs_part[self.i] = abs(vol_inc)
            if self.i == self.customized_indicator_n:
                self.customized_indicator_sma_max_part[self.i] = self.customized_indicator_max_part[self.i-self.customized_indicator_n+1:self.i+1].mean()
                self.customized_indicator_sma_abs_part[self.i] = self.customized_indicator_abs_part[self.i-self.customized_indicator_n+1:self.i+1].mean()
                self.customized_indicator[self.i] = self.customized_indicator_inc(self.customized_indicator_sma_max_part[self.i], self.customized_indicator_sma_abs_part[self.i])
            elif self.i > self.customized_indicator_n:
                self.customized_indicator_sma_max_part[self.i] = self.customized_indicator_sma_max_part[self.i-1] - self.customized_indicator_max_part[self.i-self.customized_indicator_n]/self.customized_indicator_n + self.customized_indicator_max_part[self.i]/self.customized_indicator_n
                self.customized_indicator_sma_abs_part[self.i] = self.customized_indicator_sma_abs_part[self.i-1] - self.customized_indicator_abs_part[self.i-self.customized_indicator_n]/self.customized_indicator_n + self.customized_indicator_abs_part[self.i]/self.customized_indicator_n
                self.customized_indicator[self.i] = self.customized_indicator_inc(self.customized_indicator_sma_max_part[self.i], self.customized_indicator_sma_abs_part[self.i])
                
    def cci_depends_update(self):
        # CCI 依赖变量更新
        # typical_price 已在mfi update 更新了
        if self.i >= self.cci_n-1:
            if self.i == self.cci_n-1:
                self.avg_typical_price[self.i] = self.typical_price[self.i-self.cci_n+1:self.i+1].mean()
            elif self.i > self.cci_n-1:
                self.avg_typical_price[self.i] = self.avg_typical_price[self.i-1] - self.typical_price[self.i-self.cci_n]/self.cci_n + self.typical_price[self.i]/self.cci_n
            self.mean_deviation[self.i] = abs(self.typical_price[self.i-self.cci_n+1:self.i+1] - self.avg_typical_price[self.i]).mean()
            self.cci[self.i] = self.CCI_inc(self.typical_price[self.i], self.avg_typical_price[self.i], self.mean_deviation[self.i])
                           
    def kdj_depends_update(self):
        # KDJ 依赖变量更新
        if self.i >= self.kdj_n - 1:
            self.lowest_low[self.i] = self.low[self.i+1-self.kdj_n:self.i+1].min()
            self.highest_high[self.i] = self.high[self.i+1-self.kdj_n:self.i+1].max()
            self.rsv[self.i] = (self.close[self.i] - self.lowest_low[self.i])/(self.highest_high[self.i] - self.lowest_low[self.i]) * 100
            if self.i == self.kdj_n - 1 + self.k_n - 1:
                self.k[self.i] = self.rsv[self.i+1-self.k_n:self.i+1].mean()
            elif self.i > self.kdj_n - 1 + self.k_n - 1:
                self.k[self.i] = self.k[self.i-1] - self.rsv[self.i-self.k_n]/self.k_n + self.rsv[self.i]/self.k_n
                if self.i >= self.kdj_n - 1 + self.k_n - 1 + self.d_n - 1:
                    if self.i == self.kdj_n - 1 + self.k_n - 1 + self.d_n - 1:
                        self.d[self.i] = self.k[self.i+1-self.d_n:self.i+1].mean()
                    elif self.i > self.kdj_n - 1 + self.k_n - 1 + self.d_n - 1:
                        self.d[self.i] = self.d[self.i-1] - self.k[self.i-self.d_n]/self.d_n + self.k[self.i]/self.d_n
                    self.j[self.i] = 3*self.k[self.i] - 2*self.d[self.i]    
    
    def new_bar(self, high, low, close, vol):
        self.i += 1
        self.high[self.i] = high
        self.low[self.i] = low
        self.close[self.i] = close
        self.vol[self.i] = vol
        
        self.dx_depends_update()
        self.mfi_depends_update()
        self.apo_depends_update()
        self.macd_depends_update()
        self.plus_dm_depends_update()    
        self.rsi_depends_update()
        self.tema_depends_update()
        self.customized_indicator_depends_update()
        self.cci_depends_update()
        self.kdj_depends_update()

        
    def get_indicators(self):
        return {
            'DX': self.dx[self.i],
            'ADX': self.adx[self.i],
            'MFI': self.mfi[self.i],
            'APO': self.apo[self.i],
            'MACD': self.macd[self.i],
            'MACDsignal': self.macdsignal[self.i],
            'MACDhist': self.macdhist[self.i],
            'NATR': self.natr[self.i],
            'PLUS_DM': self.plus_dm[self.i],
            'RSI': self.rsi[self.i],
            'TEMA': self.tema[self.i],
            'CUSTOMIZED_INDICATOR': self.customized_indicator[self.i],
            'CCI': self.cci[self.i],
            'RSV': self.rsv[self.i],
            'KDJ_K': self.k[self.i],
            'KDJ_D': self.d[self.i],
            'KDJ_J': self.j[self.i]
        }

In [5]:
# test

import numpy as np 

high = np.random.random(1000)
low = np.random.random(1000)
close = np.random.random(1000)
vol = np.random.random(1000)


In [7]:
ta = TAHelper()
DX = list()
ADX = list()
MFI = list()
APO = list()
MACD = list()
MACDsignal = list()
MACDhist = list()
NATR = list()
PLUS_DM = list()
RSI = list()
TEMA = list()
CUSTOMIZED_INDICATOR = list()
CCI = list()
RSV = list()
KDJ_K = list()
KDJ_D = list()
KDJ_J = list()

for i in range(len(high)):
    ta.new_bar(high[i], low[i], close[i], vol[i])
    indicators_dict = ta.get_indicators()
    DX.append(indicators_dict['DX'])
    ADX.append(indicators_dict['ADX'])
    MFI.append(indicators_dict['MFI'])
    APO.append(indicators_dict['APO'])
    MACD.append(indicators_dict['MACD'])
    MACDsignal.append(indicators_dict['MACDsignal'])
    MACDhist.append(indicators_dict['MACDhist'])
    NATR.append(indicators_dict['NATR'])
    PLUS_DM.append(indicators_dict['PLUS_DM'])
    RSI.append(indicators_dict['RSI'])
    TEMA.append(indicators_dict['TEMA'])
    CUSTOMIZED_INDICATOR.append(indicators_dict['CUSTOMIZED_INDICATOR'])
    CCI.append(indicators_dict['CCI'])
    RSV.append(indicators_dict['RSV'])
    KDJ_K.append(indicators_dict['KDJ_K'])
    KDJ_D.append(indicators_dict['KDJ_D'])
    KDJ_J.append(indicators_dict['KDJ_J'])

In [11]:
import talib 
np.set_printoptions(threshold=200)

np.array(DX) - talib.DX(high, low, close)

array([            nan,             nan,             nan, ...,
       -7.10542736e-15, -2.13162821e-14, -2.84217094e-14])

In [133]:
np.array(ADX) - talib.ADX(high, low, close)

array([           nan,            nan,            nan, ...,
       1.77635684e-15, 1.77635684e-15, 8.88178420e-16])

In [113]:
np.array(MFI) - talib.MFI(high, low, close, vol)

array([            nan,             nan,             nan, ...,
       -7.10542736e-14, -7.10542736e-14, -7.10542736e-14])

In [114]:
np.array(APO) - talib.APO(close)

array([           nan,            nan,            nan, ...,
       6.66133815e-16, 8.32667268e-16, 8.88178420e-16])

In [134]:
macd1 = np.array(MACD)
signal1 = np.array(MACDsignal)
hist1 = np.array(MACDhist)
macd2, signal2, hist2 = talib.MACD(close)

In [135]:
macd1 - macd2

array([            nan,             nan,             nan, ...,
        0.00000000e+00, -5.55111512e-17,  0.00000000e+00])

In [136]:
signal1 - signal2

array([            nan,             nan,             nan, ...,
       -2.77555756e-17, -2.77555756e-17, -2.77555756e-17])

In [137]:
hist1 - hist2

array([            nan,             nan,             nan, ...,
        2.77555756e-17, -2.77555756e-17,  2.77555756e-17])

In [119]:
np.set_printoptions(threshold=200)
np.array(NATR) - talib.NATR(high, low, close)

array([           nan,            nan,            nan, ...,
       0.00000000e+00, 0.00000000e+00, 1.42108547e-14])

In [120]:
np.set_printoptions(threshold=200)

np.array(PLUS_DM) - talib.PLUS_DM(high, low)

array([nan, nan, nan, ...,  0.,  0.,  0.])

In [124]:
np.set_printoptions(threshold=200)

np.array(RSI) - talib.RSI(close)

array([nan, nan, nan, ...,  0.,  0.,  0.])

In [125]:
np.array(TEMA) - talib.TEMA(close)

array([           nan,            nan,            nan, ...,
       2.22044605e-16, 3.33066907e-16, 0.00000000e+00])

In [12]:
np.array(CCI) - talib.CCI(high, low, close)

array([           nan,            nan,            nan, ...,
       2.30926389e-13, 1.98951966e-13, 2.41584530e-13])